version: '3'
services:
    mariadb: 
        image: 'mariadb:10.4.8'
        container_name: ${APP_NAME:?err}-mariadb
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:?err}
            MYSQL_DATABASE: ${MARIADB_DATABASE:?err}
        volumes:
        - ./docker/volumes/mariadb:/var/lib/mysql
        ports:
        - 3306:3306     
    postgresql:
        build: docker/dockerfiles/postgresql/       
        user: ${POSTGRESQL_USER:?err}
        container_name: ${APP_NAME:?err}-postgresql
        links: 
            - 'mariadb'
        environment:
            POSTGRES_USER: ${POSTGRESQL_USER:?err}
            POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD:?err}
            POSTGRES_DB: ${POSTGRESQL_DATABASE:?err}
        ports:
            - '5432:5432'
        volumes: 
            - ./docker/volumes/postgresql:/var/lib/postgresql/data 
            - ./docker/dockerfiles/postgresql/:/docker-entrypoint-initdb.d/  
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d example"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
    php:
        build: docker/dockerfiles/php/
        container_name: ${APP_NAME:?err}-php
        links: 
            - 'mariadb'
            - 'redis'
            - 'postgresql'            
        volumes:
            - '../:/var/www/html'
            - ./docker/dockerfiles/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/dockerfiles/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    redis:        
        image: redis:4.0.9        
        container_name: ${APP_NAME:?err}-redis
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning
        volumes: 
            - ./docker/volumes/redis/data:/data
    mongo:
        container_name: ${APP_NAME:?err}-mongo
        image: mongo:5.0.3
        volumes:
            - ../docker/volumes/mongo/data:/data/db
        ports:
            - '27017:27017'
    nginx:
        image: 'nginx:1.14.0'
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '80:80'
            - '9003:9003'
        links:
            - 'php'
            - 'mariadb'
            - 'redis'
            - 'postgresql'
            - 'mongo'
        volumes:
            - '../:/var/www/html'
            - './docker/dockerfiles/nginx:/etc/nginx/conf.d'