version: '3'
services:
    mysql: 
        image: 'mysql:8.0.30'
        container_name: ${APP_NAME:?err}-mysql
        restart: 'on-failure'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
            MYSQL_DATABASE: ${MYSQL_DATABASE:?err}
        volumes:
        - ./docker/volumes/mysql:/var/lib/mysql
        ports:
        - 3306:3306        
    php74:
        build: docker/dockerfiles/php_7.4/
        container_name: ${APP_NAME:?err}-php74
        links: 
            - 'mysql'
        volumes:
            - '../system:/var/www/html'
            - ./docker/dockerfiles/php_7.4/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/dockerfiles/php_7.4/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    php8:
        build: docker/dockerfiles/php_8.0/
        container_name: ${APP_NAME:?err}-php8
        links: 
            - 'mysql'
        volumes:
            - '../system:/var/www/html'
            - ./docker/dockerfiles/php_8.0/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/dockerfiles/php_8.0/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini   
        extra_hosts:
            - 'dpcs.tw:192.168.1.243'     
    redis:        
        image: redis:latest        
        container_name: ${APP_NAME:?err}-redis
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:?err}
        volumes: 
            - ./docker/volumes/redis/data:/data
    nginx:
        image: 'nginx:1.23.1'
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '80:80'
            - '9003:9003'
            - '9004:9004'
        links:
            - 'php8'
            - 'php74'
            - 'redis'
        volumes:
            - '../system:/var/www/html'
            - './docker/dockerfiles/nginx:/etc/nginx/conf.d'